M48
; DRILL file {KiCad (6.0.10)} date Mon Dec 26 18:22:23 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-12-26T18:22:23+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X137.3Y-49.5
X137.3Y-58.3
X137.3Y-66.8
X137.3Y-75.6
T2
X58.5Y-48.5
X58.5Y-76.5
X151.5Y-48.5
X151.5Y-76.5
T0
M30
