M48
; DRILL file {KiCad (6.0.9)} date Sun Dec  4 13:42:06 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-12-04T13:42:06+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X66.82Y-45.95
X66.82Y-48.554
T2
X93.263Y-50.237
X93.263Y-74.638
T3
X58.5Y-48.5
X58.5Y-76.5
X151.5Y-48.5
X151.5Y-76.5
T0
M30
