M48
; DRILL file {KiCad (6.0.10)} date Thu Jan 12 15:38:22 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-12T15:38:22+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X102.3Y-75.976
X102.3Y-78.579
T2
X93.263Y-50.237
X93.263Y-74.638
T3
X58.5Y-48.5
X58.5Y-76.5
X151.5Y-48.5
X151.5Y-76.5
T0
M30
