M48
; DRILL file {KiCad (6.0.9)} date Mon Nov 14 17:51:39 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-14T17:51:39+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X58.862Y-50.237
X58.862Y-74.638
X93.263Y-50.237
X93.263Y-74.638
T2
X65.0Y-48.5
X65.0Y-76.5
X151.5Y-48.5
X151.5Y-76.5
T0
M30
