M48
; DRILL file {KiCad (6.0.8)} date Mon Oct 31 16:03:20 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-10-31T16:03:20+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X73.5Y-57.5
X73.5Y-72.5
X73.5Y-81.5
X166.6Y-48.5
X166.6Y-81.5
T0
M30
